feat: 🎸 added new features

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,12 +3,42 @@ language: node_js
 node_js:
   - '12'
 
+env:
+  global:
+    - FORCE_COLOR=1 # Ensure colored output (color support is not detected in some cases)
+
+git:
+  # Minimize git history, but ensure to not break things:
+  # - Merging multiple PR's around same time may introduce a case where it's not
+  #   the last merge commit that is to be tested
+  # - Aside of merge commit we need a previous commit to be able to detect a version switch
+  depth: 30
+
 stages:
   - install
   - build
   - test
   - name: release
-    if: branch = master
+    if: tag =~ ^v\d+\.\d+\.\d+$
+
+before_script:
+  - set -e
+  - git config --global user.email "github@github.com"
+  - git config --global user.name "GitHub CI"
+
+# Ensure to fail build if deploy fails, Travis doesn't ensure that: https://github.com/travis-ci/travis-ci/issues/921
+before_deploy:
+  - set -e
+  # Remove eventual old npm logs
+  - rm -rf ~/.npm/_logs
+
+after_deploy:
+  - |
+    # npm creates log only on failure
+    if [ -d ~/.npm/_logs ]; then
+      # Undocumented way to force Travis build to fail
+      travis_terminate 1
+    fi
 
 jobs:
   include:
@@ -20,23 +50,31 @@ jobs:
     - stage: build
       name: 'Build'
       script:
-        - npm run build
+        - npm run all
 
     - stage: test
       name: 'Test'
       script:
-        - npm run test
+        - npm run test:all
 
     - stage: release
       name: 'Release'
       deploy:
         provider: script
         skip_cleanup: true
-        script:
-          - npx -p @semantic-release/release-notes-generator -p @semantic-release/npm -p
-            @semantic-release/github semantic-release
+        on:
+          tags: true
+        script: npx -p @semantic-release/release-notes-generator -p @semantic-release/npm -p @semantic-release/github semantic-release
 
-after_success: bash <(curl -s https://codecov.io/bash)
+after_success:
+  - bash <(curl -s https://codecov.io/bash)
+
+branches:
+  only:
+    - master # Do not build PR branches
+    - /^v\d+\.\d+\.\d+$/ # Ensure to build release tags
 
 cache:
-  directories: node_modules
+  directories:
+    - $HOME/.npm
+    - node_modules
